PPW/urls.py
from django.urls import path
from . import views

app_name = 'PPW'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('organization/', views.more, name='more'),
    path('story1/', views.story1, name='story1'),
    path('liat-jadwal/', views.savejadwal, name='savejadwal'),
    path('isi-jadwal/', views.isi, name='isi'),
    path('hapus-jadwal/<pk>', views.hapus, name='hapus'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PPW.urls')),
]

PPW/models.py
from django.db import models

class IsiJadwal(models.Model):
    nama_matkul = models.CharField(max_length=200, default='none')
    dosen_pengajar = models.CharField(max_length=200, default='none')
    jumlah_sks = models.CharField(max_length=200, default='none')
    deskripsi = models.CharField(max_length=200, default='none')
    semester = models.CharField(max_length=200, default='none')

    def __str__(self):
        return self.nama_matkul

PPW/forms.py
from django import forms
from .models import IsiJadwal

class Input_Form(forms.ModelForm):
    class Meta:
        model = IsiJadwal
        fields = [
            'nama_matkul', 'dosen_pengajar', 'jumlah_sks', 'deskripsi', 'semester'
        ]

PPW/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import IsiJadwal
from .forms import Input_Form

# Create your views here.
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def more(request):
    return render(request, 'more.html')

def story1(request):
    return render(request, 'story1.html')

def savejadwal(request):
    if (request.method == 'POST'):
        data = Input_Form(request.POST)
        if data.is_valid():
            data.save()
    show = IsiJadwal.objects.all()
    args = {'show':show}
    return render(request, 'jadwal.html', args)

def isi(request):
    return render(request, 'isi.html')

def hapus(request, pk):
    hapus = IsiJadwal.objects.filter(id=pk)    
    hapus.delete()
    return HttpResponseRedirect('/liat-jadwal/')

PPW/templates/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>About Me</title>
    </head>

    <body>
        <h1 class="aboutme">About Me</h1>
        <br>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12 text">
                    <article>I’m a college student of Computer Science at University of Indonesia. I’m a man of focus, commitment, and sheer will</article>
                    <article>Just contact me if you want to know more about me</article>
                    <article>Peace, love, and gaul ;)</article>
                </div>
            </div>
        </div>
        
        <h1 class="project">Project</h1>
        <br>
        <div class="container-fluid">
            <div class="row justify-content-center align-items-center background">
                <div class="col-lg-3 margin">
                    <img class="airbuspic" src="https://profile.line-scdn.net/0m0e49d2db725190e555d410aa11cdb98a2971c06c40f7/preview" alt="Airbus">
                </div>
                <div class="col-lg-9 margin">
                    <p class="judul">Airbus</p>
                    <p class="isi">Airbus is a service start-up that provides rental for school needs such as school hats, school ties, lab coats, print your schoolwork, and many more.
                    Unfortunately this start-up just available on my high school only.</p>
                </div>
            </div>
        </div>
        <br>
        <br>

    </body>
</html>

PPW/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Homepage</title>
    </head>
    
    <body>
        <div class="container awal">
            <div class="row justify-content-center">
                <div class="col-md-4 text-center">
                    <img class="self center-block" src="https://maung.id/static/3218f16a5414379bac2e0ca2bc5b348b/9f583/KR09.jpg" alt="Aryuda O.">
                    <br>
                    <a class="source" href="https://maung.id/aryuda.oktawyandra" target="_blank">Source</a>
                </div>
                <div class="col-md-8">
                    <h2 class="hello">Hello People</h2>
                    <article class="welcome">My name is Yuda, and welcome to my web</article>
                    <article class="welcome">Please don’t leave your seat, and make sure to fasten your seat belt</article>
                    <article class="welcome">Enjoy your time :)</article>
                </div>                
            </div>      
        </div>

        <h1 class="edu">Education Background</h1>
        <br>

        <div class="container">
            <div class="row text-center justify-content-center">
                <div class="col-md-3 background">
                    <h3 class="class">Junior High School</h3>
                    <img class="classpic center-block" src="https://4.bp.blogspot.com/-o6pJdteu8C4/UOA_-7Q6PWI/AAAAAAAAJc8/9dj8WgFLCy0/s1600/LOGO+OSIS+SMP.png" alt="Logo SMP">
                    <h4 class="place">SMPN 91 Jakarta</h4>
                </div>
                <div class="col-md-3 offset-sm-1 background">
                    <h3 class="class">Senior High School</h3>
                    <img class="classpic center-block" src="https://1.bp.blogspot.com/-k1X-FZql9z4/UOA_sQfMy2I/AAAAAAAAJc0/OibdJLa5tAU/s1600/LOGO+OSIS+SMA.png" alt="Logo SMA">
                    <h4 class="place">SMAN 39 Jakarta</h4>
                </div>
                <div class="col-md-3 offset-sm-1 background">
                    <h3 class="class">College University</h3>
                    <img class="UIpic center-block" src="https://upload.wikimedia.org/wikipedia/id/thumb/9/95/Makara_UI.png/1200px-Makara_UI.png" alt="Logo UI">
                    <h4 class="place">University of Indonesia</h4>
                </div>
            </div>
        </div>

        <h1 class="contact">Contact Me</h1>
        <table class="excontact">
            <th>
                <td>
                    <a href="https://line.me/R/ti/p/aryuda145" target="_blank">
                        <img class="line" src="{% static 'Images/line.png' %}" alt="Line">
                    </a>
                    <a href="https://wa.me/+6281212945027" target="_blank">
                        <img class="whatsapp" src="{% static 'Images/whatsapp.png' %}" alt="Whatsapp">
                    </a>
                    <a href="https://id.linkedin.com/in/aryuda-oktawyandra-2703bb195" target="_blank">
                        <img class="linkedin" src="{% static 'Images/linkedin.png' %}" alt="LinkedIn">
                    </a>
                </td>
            </th>
        </table>
        <br>

    </body>

</html>

PPW/templates/isi.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'jadwal.css' %}">
        <title>Isi jadwal</title>
    </head>

    <body>
        <div class="container-xl form">
            <form action="{% url 'PPW:savejadwal' %}" method="POST">
                {% csrf_token %}

                <div class="row justify-content-center">
                    <div class="col-sm-4">
                        <label for="nama_matkul">Course</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="input" type="text" id="nama_matkul" name="nama_matkul" placeholder="Ex: Calculus 3" required>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-sm-4">
                        <label for="dosen_pengajar">Lecturer</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="input" type="text" id="dosen_pengajar" name="dosen_pengajar" placeholder="Ex: Aryuda Oktawyandra" required>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-sm-4">
                        <label for="jumlah_sks">Number of Credits</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="input" type="text" id="jumlah_sks" name="jumlah_sks" placeholder="Ex: 4" required>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-sm-4">
                        <label for="deskripsi">Description</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="input" type="text" id="deskripsi" name="deskripsi" placeholder="Ex: Easy peasy" required>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-sm-4">
                        <label for="semester">Semester</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="input" type="text" id="semester" name="semester" placeholder="Ex: Genap 2019/2020" required>
                    </div>
                </div>

                <div class="row text-right justify-content-center">
                    <div class="col-sm-12">
                        <input class="submit" type="submit" value="Submit">
                    </div>
                </div>
            
            </form>
        </div>

    </body>

</html>

PPW/templates/jadwal.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'jadwal.css' %}">
        <title>Jadwal</title>
    </head>

    <body>
        <div class="tabel">
            <table>
                <tr>
                    <th>Courses</th>
                    <th>Lecturer</th>
                    <th>Number of Credits</th>
                    <th>Description</th>
                    <th>Semester</th>
                    <th class="blank"></th>
                </tr>
                {% if show %}
                    {% for list in show %}
                        <tr>
                            <td>{{ list.nama_matkul }}</td>
                            <td>{{ list.dosen_pengajar }}</td>
                            <td class="tengah">{{ list.jumlah_sks }}</td>
                            <td>{{ list.deskripsi }}</td>
                            <td class="tengah">{{ list.semester }}</td>
                            <td class="blank">
                                <a type="button" class="btn btn-outline-danger" href="{% url 'PPW:hapus' list.pk %}" onclick="return confirm('U sure bro?');">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>

        <div class="container">
            <div class="row text-center justify-content-center">
                <div class="col-md-2">
                    <a href="{% url 'PPW:isi' %}">
                        <button type="button" class="add">Add yours</button>
                    </a>
                </div>
            </div>
        </div>
    
    </body>

</html>

PPW/templates/more.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Organization</title>
    </head>

    <body>
        <h1 class="organization">Organization Experience</h1>
        <br>
        <div class="container-fluid">
            <div class="row justify-content-center align-items-center background">
                <div class="col-lg-3 margin">
                    <img class="pic" src="https://pbs.twimg.com/profile_images/1237361109960552449/ssdSXeSS_400x400.jpg" alt="Compfest">
                </div>
                <div class="col-lg-9 margin">
                    <p class="judul">COMPFEST</p>
                    <p class="isi">COMPFEST is an annual one-stop IT event run by students of the Faculty of Computer Science, University of Indonesia.</p>
                </div>
            </div>
        </div>

        <br>

        <div class="container-fluid">
            <div class="row justify-content-center align-items-center background">
                <div class="col-lg-3 margin">
                    <img class="pic" src="https://pbs.twimg.com/profile_images/1208613351615418369/tRyrgKyl_400x400.jpg" alt="PERAK">
                </div>
                <div class="col-lg-9 margin">
                    <p class="judul">PERAK</p>
                    <p class="isi">PERAK is the biggest internal event at Faculty of Computer Science, University of Indonesia which aims to maintain a sense of kinship between elements</p>
                </div>
            </div>
        </div>

        <br><br>
        
    </body>
</html>

PPW/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark topnav">
      <a class="navbar-link" href="{% url 'PPW:index' %}">
        <h5 class="home">Home</h5>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'PPW:more' %}">
            <h5>Organization</h5>
          </a>
          <a class="nav-link" href="{% url 'PPW:about' %}">
            <h5>About Me</h5>
          </a>
          <a class="nav-link" href="{% url 'PPW:savejadwal' %}">
            <h5>Jadwal</h5>
          </a>
          <a class="nav-link" href="{% url 'PPW:story1' %}">
            <h5>Story 1</h5>
          </a>
        </div>
      </div>
    </nav>

  </body>
</html>

PPW/templates/story1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Story 1 PPW</title>

        <style>
            body {
                background-color: #e8e8e8;
            }
            h1 {
                text-align: center;
            }
            .head {
                font-size: 50px;
                color: darkcyan;
            }
            .self {
                float: left;
                width: 203px;
                height: 305px;
            }
            .biodata table {
                float: right;
                height: 300px;
                font-size: 25px;
                color: maroon;
            }
            .riwayat table, .riwayat th, .riwayat td {
                border: 2px solid darkslategray;
            }
            .riwayat table {
                margin-top: 50px;
                margin-left: auto;
                margin-right: auto;
                border-collapse: collapse;
                width: 500px;
            }
            .riwayat th, .riwayat td {
                padding: 10px;
                color: white;
                background-color: #07070a;
            }
            .riwayat th {
                color: palevioletred
            }
            .riwayat th:hover, .riwayat td:hover {
                background-color: gray;
            }
            .line {
                float: left;
                width: 50px;
                height: 50px;
            }
            .whatsapp {
                float: right;
                width: 50px;
                height: 50px;
            }
            .awal {
                margin-left: auto;
                margin-right: auto;
                width: 60%;
            }
            .contact {
                margin-left: auto;
                margin-right: auto;
                width: 12%;
            }
            .spasi {
                padding-left: 30px;
            }   
        </style>
    </head>

    <body>
        <h1 class="head">Informasi Data Diri</h1>
        <br>
        <table class="awal">
            <tr>
                <td>
                    <img class="self" src="https://maung.id/static/3218f16a5414379bac2e0ca2bc5b348b/9f583/KR09.jpg" alt="Aryuda O.">
                    <div class="biodata">
                        <table>
                            <tr>
                                <td>Nama</td>
                                <td class="spasi">: Aryuda Oktawyandra</td>
                            </tr>
                            <tr>
                                <td>NPM</td>
                                <td class="spasi">: 1906307542</td>
                            </tr>
                            <tr>
                                <td>Angkatan</td>
                                <td class="spasi">: 2019</td>
                            </tr>
                            <tr>
                                <td>Tempat Kuliah</td>
                                <td class="spasi">: Universitas Indonesia</td>
                            </tr>
                            <tr>
                                <td>Hobi</td>
                                <td class="spasi">: Semangatin orang lain</td>
                            </tr>
                            <tr>
                                <td>Deskripsi Diri</td>
                                <td class="spasi">: Anak ke-2 dari dua bersaudara</td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>

        <div class="riwayat">
            <table>
                <tr style="text-align: center; font-size: 20px;">
                    <th>Jenjang Pendidikan</th>
                    <th>Tahun</th>
                </tr>
                <tr>
                    <td>SDN Pekayon 15 Pagi</td>
                    <td style="text-align: center;">2007 - 2013</td>
                </tr>
                <tr>
                    <td>SMPN 91 Jakarta</td>
                    <td style="text-align: center;">2013 - 2016</td>
                </tr>
                <tr>
                    <td>SMAN 39 Jakarta</td>
                    <td style="text-align: center;">2016 - 2019</td>
                </tr>
                <tr>
                    <td>Universitas Indonesia</td>
                    <td style="text-align: center;">2019 - Sekarang</td>
                </tr>
            </table>
        </div>
        <br>

    </body>
</html>